# Generated by Django 4.2.3 on 2023-07-31 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_person', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('date_creation', models.DateTimeField(verbose_name='Date creation')),
                ('views', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NumberTel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_number', models.CharField(max_length=80)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managerContact.person')),
            ],
        ),
    ]
