# Generated by Django 4.2.3 on 2023-07-31 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managerContact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numbertel',
            name='other_number',
            field=models.CharField(max_length=100),
        ),
    ]
