# Generated by Django 4.2.3 on 2023-07-28 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managerContact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='name_person',
        ),
    ]
