# Generated by Django 4.2.3 on 2023-07-28 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managerContact', '0002_rename_name_person_name_person'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Numbers',
            new_name='NumberTel',
        ),
    ]
