# Generated by Django 4.2.3 on 2023-07-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managerContact', '0003_rename_numbers_numbertel'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='views',
            field=models.BooleanField(default=True),
        ),
    ]
